#!/usr/bin/env python3
"""Regenerate FLAGS.md from the solve artifacts under chal/.

The transcript is lossy (compaction has already destroyed flags once), so the
repo is the durable record. Run this after every merge, or via tools/land.sh.

    python3 tools/flags.py            # rewrite FLAGS.md
    python3 tools/flags.py --count    # print "N challenges" only
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAT = re.compile(r"safctf\{[0-9a-zA-Z_\-]{8,}\}")


def collect():
    """{challenge_dir: {flag: source_path}}, from every NOTES.md / solve.py."""
    rows = {}
    for p in sorted((ROOT / "chal").rglob("*")):
        if p.suffix not in (".md", ".py") or not p.is_file():
            continue
        for flag in PAT.findall(p.read_text(errors="ignore")):
            rows.setdefault(str(p.parent.relative_to(ROOT / "chal")), {})[flag] = \
                str(p.relative_to(ROOT))
    return rows


def main():
    rows = collect()
    if "--count" in sys.argv:
        print(len(rows))
        return 0

    out = [
        "# Safaricom CTF — captured flags", "",
        "Durable record, regenerated by `tools/flags.py` (call it via "
        "`tools/land.sh` after a merge).",
        "The repo — not the chat transcript — is the source of truth: compaction "
        "has already destroyed captured flags once.", "",
        "Desk-app challenges yield **two** flags: an intermediate `answer` "
        "(a receipt you reconstruct and POST to `/submit`) and the graded flag "
        "that comes back. `NOTES.md` says which is which.", "",
        "| Challenge | Flag | Source |", "| --- | --- | --- |",
    ]
    for name in sorted(rows):
        for flag, src in sorted(rows[name].items()):
            out.append(f"| {name} | `{flag}` | {src} |")
    (ROOT / "FLAGS.md").write_text("\n".join(out) + "\n")
    print(f"{len(rows)} challenges, {sum(len(v) for v in rows.values())} flags")
    return 0


if __name__ == "__main__":
    sys.exit(main())
